server:
  port: 8091

spring:
  application:
    name: customer-services
  
  main:
    banner-mode: off

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB
    username: customer
    password: ins123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure: 
        include: "*"
        
  info:
    env:
      enabled: true

info:
  app:
    name: customer-service
    description: Customer microservice for insurance system
    version: 1.0

logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.springframework.web: INFO
    org.springframework.data: ERROR
    com.zaxxer.hikari: ERROR
